[package]
name = "arena-interner"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.3"
bumpalo = { version = "3.12", features = ["boxed", "collections"] }
generativity = "1.0.1"
hashbrown = { version = "0.13.2", features = ["ahash"] }

[dev-dependencies]
trybuild = "1.0"
